/* file: v40init.h */

/****************************************************************************
 *
 *      v40 hardware header file
 *
 *      written by denton marlowe
 *      (c)1990 Hayes Targets
 *
 ***************************************************************************/

/*@R*************************************************************************
 *
 *      Revision History
 *
 *      Date            Engineer        Description
 *
 *      02/06/90        D.marlowe       Original release
 *
 ************************************************************************@R*/

/****************************************************************************
 *
 *      V40 Hardware initialization function prototypes
 *
 ***************************************************************************/

 void v40_init(void);           /* initialize V40 specific hardware */
 void v20_init(void);           /* initialize V20 specific hardware */
