/* file: terminal.h */

/****************************************************************************
 *
 *	Ground test functions header file
 *
 *      written by denton marlowe
 *	(c)1991 Hayes Targets
 *
 ***************************************************************************/

/****************************************************************************
 *
 *       COMM Port test function prototypes
 *
 ***************************************************************************/

 void term(void);			/* terminal loop-back test */
 int com_break(void);			/* test comm ports for access */
