|9A|            ; Insure at top level menu, invoke (A)utoTest menu
MA              ; (M)essage, (A)lways
'*  START OF 2564 PROM SELECT BATCH FILE  *'
|9P|            ; Return to top level menu, invoke PROM programmer menu
T|R|R|R|        ; change PROM type to 2564
|9A|            ; Insure at top level menu, invoke (A)utoTest menu
MA              ; (M)essage, (A)lways
'********   END OF 2564 PROM SELECT BATCH FILE   ******'
:end
