/* file: menu_sta.h */

/****************************************************************************
 *
 *	Ground test functions header file
 *
 *	written by denton marlowe
 *	(c)1991 Hayes Targets
 *
 ***************************************************************************/

/****************************************************************************
 *
 *	STATUS serial interface function prototypes
 *
 ***************************************************************************/

 void status_menu(void);
 void status_status(void);
 void status_test(void);
 void led_report(int status);
 void status_config_display(void);
 void status_sequence_test(void);
