/* file: menu_rtc.h */

/****************************************************************************
 *
 *	Ground test functions header file
 *
 *      written by denton marlowe
 *	(c)1991 Hayes Targets
 *
 ***************************************************************************/

/****************************************************************************
 *
 *      RTC serial interface function prototypes
 *
 ***************************************************************************/

 void rtc_menu(void);           /* RTC functions menu */
 void set_time(void);           /* set time */
 void set_date(void);           /* set data */
 void display_clock(void);      /* display clock */
