/* file: menu_rlc.h */

/****************************************************************************
 *
 *	Ground test functions header file
 *
 *	written by denton marlowe
 *	(c)1991 Hayes Targets
 *
 ***************************************************************************/

/****************************************************************************
 *
 *	RLC serial interface function prototypes
 *
 ***************************************************************************/

 void rlc_menu(void);
 void rlc_status(void);
 void rlc_test(void);
 void rlc_report(int status);
 void rlc_config_display(void);
 void rlc_sequence_test(void);
