/* file: menu_sbx.h */

/****************************************************************************
 *
 *	Ground test functions header file
 *
 *	written by denton marlowe
 *	(c)1991 Hayes Targets
 *
 ***************************************************************************/

/****************************************************************************
 *
 *	LPM-SBX function prototypes
 *
 ***************************************************************************/

 void lpm_sbx_menu(void);
 void loop_LPM_SBX(void);
 void lpm_sbx_config_display(void);
